### ISSUE TITLE
Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by daleharvey** [dave1010/jquery-fast-click#2]
Attempting to use $.Fastclick to improve the clickspeed on existing links on a HTC desire android 2.2 with the stock browser

$('a, button').fastClick(function() {
  alert('clicked!');
});

http://couch.arandomurl.com/couchtasks/_design/couchtasks/fastclick.html

E/browser (  936): Console: Uncaught TypeError: Cannot read property '0' of undefined http://couch.arandomurl.com/couchtasks/_design/couchtasks/js/jQuery.fastClick.js:57

switching to event.originalEvent.touches gives 

E/browser (  936): Console: Uncaught TypeError: Cannot read property 'clientX' of undefined http://couch.arandomurl.com/couchtasks/_design/couchtasks/js/jQuery.fastClick.js:58

tested with jquery-git and jquery-1.5.2

**Comment by dave1010** [comment]
Thanks for the bug report. I'm not sure why `touches` is undefined there. Not at a computer now to debug it. What do you get if you do: `console.log(event)` on line 57? (You can use jsconsole.com to get a remote console on your HTC.)

**Comment by dave1010** [comment]
It may be the HTC doesn't populate the event object at that time. Does it make any difference if you wrap lines 57 & 58 in a `setTimeout(function(){ ... }, 1)`?

**Comment by nizzy** [comment]
Hi Dave,

I couldn't make your fastclick.js work on Android phones at all. I don't see any console error either. I am not sure it's the same problem as the previous poster said. I set the fastClick event on anchor link and wasn't able to see alert.

I checked the original google code, you don't have handleEvent function.
google.ui.FastButton.prototype.handleEvent = function(event) {
  switch (event.type) {
    case 'touchstart': this.onTouchStart(event); break;
    case 'touchmove': this.onTouchMove(event); break;
    case 'touchend': this.onClick(event); break;
    case 'click': this.onClick(event); break;
  }
};

any idea how to fix it?

**Comment by nizzy** [comment]
Dave, never mind!

It was my fault. I was trying to call fastClick before domready.

Thank you.

**Comment by nizzy** [comment]
Dave,

onTouchStart event returns the following list of properties. I don't see touches there at all. This is on Android/Samsun nexus s.

originalEvent, type, isDefaultPrevented, timeStamp, jQuery15103799102194607258, which, wheelDelta, view, toElement, target, srcElement, shiftKey, screenY, screenX, relatedTarget, relatedNode, prevValue, pageY, pageX, offsetY, offsetX, newValue, metaKey, layerY, layerX, keyCode, handler, fromElement, eventPhase, detail, data, currentTarget, ctrlKey, clientY, clientX, charCode, cancelable, button, bubbles, attrName, attrChange, altKey, namespace, handleObj, isPropagationStopped

**Comment by dave1010** [comment]
That's strange. I don't have an Android device to test on at the moment. Does it work if you change `event.touches[0].clientX` to `event.clientX` (and the same for `clientY`?

**Comment by nizzy** [comment]
well, without those touch properties, click speed on Android phones is already equivalent to fast click. I made 20 click tests with/out fastClick.js. Both have almost identical results.

I bet this issue might be related to iPhones.

**Comment by dave1010** [comment]
This should be fixed by #6 (props @KyleAMathews).

**Comment by mcasimir** [comment]
Still valid for some device? https://github.com/mcasimir/mobile-angular-ui/issues/187

In chrome device mode Fastclick still fires this exception, although i think (and hope) is an emulation issue.
