### ISSUE TITLE
Break a doubleClick / doubleTap ?

### ISSUE THREAD

**Issue by tekmonk** [dave1010/jquery-fast-click#3]
I somehow managed to make your plugin work with xui.js for the time being, and it definitely makes a web app more responsive then the click events.  

Everything seems to work great (week or so now) until you "double tap" something.   Then all hell breaks loose.  Granted, I think very few mobile users are 'double tapping' stuff to navigate around, but even an accidental double-tap can cause the links to break.  

I'm not even sure if "double tap" events exist in Webkit, so I'm not really sure what is causing the problem.  Would setting the timeout on "preventghostClick"  to a lower interval help?

**Comment by dave1010** [comment]
Glad you got it working. I'm not sure about doubleclicking. preventghostClick should help. I'm not near a WebKit device at the moment to try it out.

**Comment by dave1010** [comment]
Did you have to change much to get it working with xui? Would be great of you could share the code.

**Comment by tekmonk** [comment]
It is essentially the same thing, except the xuijs hook is x$, rather than $ in jQuery. And instead of bind i use "on"   There's also some stuff commented out in there for adding styles and stuff to buttons dynamically.  

https://gist.github.com/1406903

But a bigger problem has arose.  While this script worked fine within an Android browser, I have begun the process of making it into an application with Phonegap.  

As soon as I do that, I've lost any ability to click

TypeError: Result of expression 'event.touches[0]' [undefined] is not an object. at file:///android_asset/www/js/mywebapplogic.js

After some quick research, it doesn't look like event.touches[0] is a supported property in Android, just iOS.  I  will definitely keep digging though

**Comment by tekmonk** [comment]
Nevermind I just realized the other open issue is related to my problem [ https://github.com/dave1010/jquery-fast-click/issues/2] .  I might just have to scrap this script all together for App development (although it seemed to be working fine in the browser )

**Comment by dave1010** [comment]
This should be fixed by #6 (props @KyleAMathews).
