### ISSUE TITLE
this variable is Window object

### ISSUE THREAD

**Issue by jnormore** [dave1010/jquery-fast-click#4]
$(".button").fastClick(function() {
    console.debug(this.toString());
}

outputs [object Window], when it should output [object HtmlDivElement] (or whatever the button class is defined in). Any help would be appreciated.

Thanks.

**Comment by jnormore** [comment]
Figured it out, solution is to change the handler call in onClick (line 37) to 

handler.call(this, event);

**Comment by erictutlys** [comment]
This helped me out, thanks!

Any reason this shouldn't be the default?

**Comment by dave1010** [comment]
This looks right. Could you submit a pull request?

**Comment by dave1010** [comment]
Fixed by pull request #10. Props @jnormore
