### ISSUE TITLE
Code not removing delay 

### ISSUE THREAD

**Issue by ganmor** [dave1010/jquery-fast-click#5]
This code does _not_  seem to prevent delay.
( It does not on ios anyway )

**Comment by dave1010** [comment]
@ganmor thanks for the feedback. Could you try it with the latest version? Also, what version of iOS are you using?

**Comment by dave1010** [comment]
@ganmor Is this still an issue?

**Comment by ganmor** [comment]
Sorry for the late reply.
I ended up rewriting wrong

**Comment by ganmor** [comment]
Sorry for the late answer .
I ended up rewriting my own plugin because I needed it on the moment.

I will try to test your code when I get a chance.
